### PR TITLE
Merge Model and ModelUpdate

### PR DESCRIPTION
**Pull request by GeoffreyFrogeye**
## Description

To better understand this diff:

- Compare https://api-docs.firefly-iii.org/ with https://geoffrey.frogeye.fr/files/GKG3AwwsjjvvQk7y/api-docs-mergeupdate3/
- Compare the old `AccountUpdate.yaml` with the new `Account.yaml` since GitHub did not catch the rename

What do you think? Should I continue in this direction?

Pros:
 
- Less source material, better maintainability
- Will allow to identify fields that are not consistent between the read and the write operations in the API (as seen here with the `writeOnly` tag)

Cons:

- Read operations will sometimes have their description tainted with write-only related material and vice-versa

## Merging progress

- [x] AccountUpdate.yaml
- [x] AttachmentUpdate.yaml
- [x] AvailableBudgetUpdate.yaml
- [x] BillUpdate.yaml
- [x] BudgetLimitUpdate.yaml
- [x] BudgetUpdate.yaml
- [x] CategoryUpdate.yaml
- [x] CurrencyUpdate.yaml
- [x] LinkTypeUpdate.yaml
- [x] PiggyBankUpdate.yaml
- [x] PreferenceUpdate.yaml
- [x] RecurrenceRepetitionUpdate.yaml
- [x] RecurrenceTransactionUpdate.yaml
- [x] RecurrenceUpdate.yaml
- [x] RuleActionUpdate.yaml
- [x] RuleGroupUpdate.yaml
- [x] RuleTriggerUpdate.yaml
- [x] RuleUpdate.yaml
- [x] TagUpdate.yaml
- [x] TransactionLinkUpdate.yaml
- [x] TransactionSplitUpdate.yaml
- [x] TransactionUpdate.yaml
- [x] UserUpdate.yaml

## Testing

(I have some tests to verify the consistency of the API. Before merging this PR, I want to make sure that everything still works. Those things are in the road of the 100% coverage)

- [x] https://github.com/firefly-iii/firefly-iii/issues/2477
- [x] https://github.com/firefly-iii/firefly-iii/issues/2483
- [x] https://github.com/firefly-iii/firefly-iii/issues/2485
- [ ] Implementing Attachement file upload
- [ ] Implementing Preference tests

Also

- [x] Fix the commit history on this branch :man_shrugging:

### CODE REVIEW

**Comment by GeoffreyFrogeye** [comment]
(sorry, deleted the wrong branch)

**Comment by JC5** [comment]
No please continue, I appreciate all the hard work. Direct me if you think Firefly III needs fixes to remove inconsistencies, like the attachment thing.

When you're ready to merge let me know and I'll pull it in.

**Comment by GeoffreyFrogeye** [comment]
(don't worry, this is part of the history-rewrite process)

**Comment by GeoffreyFrogeye** [comment]
@JC5 This is ready to be merged!

There are some things that I did not test, but I did not test them before I started working on this either, so I have nothing to compare with. This will be done in due time.

This also include some changes following the changes in https://github.com/firefly-iii/firefly-iii/issues/2483 and https://github.com/firefly-iii/firefly-iii/issues/2475#issuecomment-527792376, since I couldn't bother separating everything. Do tell me if this is a concern.

**Comment by JC5** [comment]
Not a concern. Thanks a lot for all of your efforts :+1: !

**Pull request merged**
